# Generated by Django 5.1.7 on 2025-03-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_checkoutaddress_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_order_id',
            new_name='esewa_payment_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_payment_id',
            new_name='product_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
    ]
